# Generated by Django 4.0.2 on 2022-02-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("modified_date", models.DateField()),
                ("jpg_file", models.FileField(upload_to="")),
                ("yrd_file", models.FileField(upload_to="")),
                ("his_file", models.FileField(upload_to="")),
            ],
        ),
    ]
