# Generated by Django 4.0.2 on 2022-02-21 19:46

from django.db import migrations, models

import fymserver.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "train_file",
                    models.FileField(
                        storage=fymserver.storage_backends.TrainDataS3Storage(),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
