# Generated by Django 4.0.2 on 2022-03-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="downloaded_by",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
