# Generated by Django 4.0.2 on 2022-03-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
        ("trains", "0002_alter_train_downloaded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="downloaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="players.player",
            ),
        ),
    ]
