# Generated by Django 4.0.2 on 2022-05-15 16:56

from django.db import migrations, models

import players.models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="token",
            field=models.CharField(
                default=players.models.generate_token, max_length=128
            ),
        ),
    ]
