# Generated by Django 4.0.2 on 2022-05-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_player_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="email",
            field=models.CharField(default="test@localhost", max_length=200),
            preserve_default=False,
        ),
    ]
